/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Dogs {
	String name;
	String color;
	String breed;
	Boolean hungry = false;

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getColor() {
		return color;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	public String getBreed() {
		return breed;
	}

	public void setHungry(Boolean hungry) {
		this.hungry = hungry;
	}

	public Boolean getHungry() {
		return hungry;
	}

	public static void main(String[] args) {
		Dogs firstDog = new Dogs();
		firstDog.setName("boby");
		firstDog.setBreed("asian");
		firstDog.setColor("black");
		firstDog.getName();
		System.out.print(firstDog.getName() + "is an " + firstDog.getBreed() + "dog");
	}
}
