/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class DogsTest {
    @Test public void testAppHasAGreeting() {
        Dogs classUnderTest = new Dogs();
        assertNotNull("app should have a greeting", classUnderTest.getName());
    }

	private void assertNotNull(String string, String name) {
		// TODO Auto-generated method stub
		
	}
}
